- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "refactor"
  color: "B06E16"
  description: "Change in the structure"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "meta"
  color: "1D76DB"
  description: "Something related to the project itself"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "help wanted"
  color: "008672"
  description: "Extra help is needed"
- name: "urgent"
  color: "D93F0B"
  description: ""
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"
