[package]
name = "reCTBNpy"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
numpy = "*"
reCTBN = { path="../reCTBN" }
